removing CLI notebook
glotzerlab/signac-examples pull request #27
Opened 2021-02-11 19:50 UTC by atravitz

The command line interface notebook is very outdated and I don't think it's a useful example anymore. I think  any additional CLI documentation should be added to the signac [Command Line Interface docs page](https://docs.signac.io/projects/core/en/latest/cli.html).

2021-02-12 12:32 UTC, tommy-waltmann commented
Is there information/examples on advanced indexing elsewhere in the documentation?

2021-02-13 01:46 UTC, atravitz commented
> Is there information/examples on advanced indexing elsewhere in the documentation?

[Here](https://docs.signac.io/en/latest/indexing.html?highlight=indexing#concept) are our current docs for indexing. I'd like some feedback from folks on what they use it for and what type of docs would be helpful

2021-02-15 13:34 UTC, tommy-waltmann commented
I haven't used the advanced indexing, feedback from others would be more useful here.

2021-02-15 22:55 UTC, bdice requested changes
We need to update `index.ipynb`, then this can be merged. We can re-organize the notebooks in a separate PR. I'm fine with leaving them numbered as they are (with nothing named "201") until we delete all the content we know we don't want.

2021-02-15 22:57 UTC, bdice commented
@tommy-waltmann We discussed at signac dev meeting today -- basically all of the indexing-related APIs are deprecated (indexing can be somewhat useful for internal purposes but is not needed in the public API), so we will be reducing our discussion of indexing in docs and tutorials.

2021-02-15 23:33 UTC, bdice commented
In @mikemhenry's review of #22, he suggested deleting notebooks 203 and 204 as well.

- 203 is definitely deprecated and can be removed.
- 204 is only marginally useful, if you need CLI wizardry or integration with a bash script. It says it is deprecated but I don't see the deprecated pieces. I think it's just not helpful.

@atravitz What do you think about deleting those two notebooks?

2021-02-16 14:55 UTC, atravitz commented
> In @mikemhenry's review of #22, he suggested deleting notebooks 203 and 204 as well.
> 
> * 203 is definitely deprecated and can be removed.
> * 204 is only marginally useful, if you need CLI wizardry or integration with a bash script. It says it is deprecated but I don't see the deprecated pieces. I think it's just not helpful.
> 
> @atravitz What do you think about deleting those two notebooks?

I agree, I think 204 is very esoteric. We might want to add more examples of integrating with non-python workflows, but  I say remove this.

2021-02-16 15:02 UTC, atravitz commented
Now that we've stripped out the unnecessary examples, it's looking a little sparse. 

![image](https://user-images.githubusercontent.com/31974495/108080253-a7796980-703d-11eb-9e71-731e157bad64.png)


I'd like people's thoughts on what else would be good content for examples. @bdice, @tommy-waltmann, @cbkerr, @kidrahahjo: what do you think about merging the [Advanced How-To](https://docs.signac.io/en/latest/recipes.html) section in with these examples to keep all these similar references in the same place? (at least as a temporary measure until we add more content)

2021-02-16 15:16 UTC, bdice commented
@atravitz I think the Advanced How-To “recipes” section can become a set of notebooks, yes. But I would prioritize reorganizing the notebooks and merging the tutorial rST files with our existing notebooks first.

2021-02-16 15:43 UTC, cbkerr commented
> what do you think about merging the Advanced How-To section in with these examples to keep all these similar references in the same place? 

@atravitz I think Examples and Tutorial sections are closer in scope than Examples and Advanced How To. Not all advice in Advanced How To fits as "Getting Started" material to someone first learning about the project.

> (at least as a temporary measure until we add more content)

I would caution against temporary moves unless it is showing up in both places at once.
For example, @AlainKadar mentioned losing something in the docs over the past months and I'd like to minimize that kind of thing happening.

2021-02-16 22:36 UTC, atravitz commented
> > what do you think about merging the Advanced How-To section in with these examples to keep all these similar references in the same place?
> 
> @atravitz I think "Examples" and "Tutorial" sections are closer in scope than "Examples" and "Advanced How To". Not all advice in Advanced How To fits as "Getting Started" material to someone first learning about the project.
> 
> > (at least as a temporary measure until we add more content)
> 
> I would caution against temporary moves unless it is showing up in both places at once.
> For example, @AlainKadar mentioned losing something in the docs over the past months and I'd like to minimize that kind of thing happening.

In that case, I think the pandas example should be grouped with How-Tos. So
- remove pandas example here (or leave it as section 1.8)
- merge tutorials with examples
and
- make advanced how-tos notebooks
- add the pandas content to the how-tos

2021-05-03 13:29 UTC, tcmoore3 requested changes
Need to make sure the updated `index.ipynb` matches which files are actually removed.

2021-05-03 13:29 UTC, tcmoore3 commented on notebooks/index.ipynb
>      "* [1.5 Command Line Interface (CLI)](signac_105_Command_Line_Interface.ipynb)\n",
This notebook was removed, right?

2021-05-27 17:41 UTC, bdice approved these changes
I rewrote some notebooks using outdated FlowProject syntax. I'm going to merge this once CI passes -- this PR is a huge improvement over the current state of affairs.

2021-05-27 17:44 UTC, merged